[package]
name = "dontupload/thieves"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
# Signal = "sleitnick/signal@2.0.1"
# Sift = "csqrl/sift@0.0.8"
Observers = "sleitnick/observers@0.3.4"
FractalitySpring = "egomoose/fractality-spring@0.2.0"
conch = "alicesaidhi/conch@0.2.4"
conch_ui = "alicesaidhi/conch-ui@0.2.4"
imgizmo = "jakeywastaken/imgizmo@^3.5.0"
ui_labs = "pepeeltoro41/ui-labs@2.4.1"