-- generated!
export type CollectionEntry = {
	Name: string,
	AssetId: string,
	AssetSetId: string,
	AssetVersionId: string,
	CreatorName: string,
	IsTrusted: boolean,
}

return {
	["360380"] = require("@self/360380"),
	["360378"] = require("@self/360378"),
	["360375"] = require("@self/360375"),
	["360372"] = require("@self/360372"),
	["360371"] = require("@self/360371"),
	["360369"] = require("@self/360369"),
	["360365"] = require("@self/360365"),
	["360363"] = require("@self/360363"),
	["360362"] = require("@self/360362"),
	["360360"] = require("@self/360360"),
	["438059"] = require("@self/438059"),
	["433570"] = require("@self/433570"),
	["400993"] = require("@self/400993"),
	["462226"] = require("@self/462226"),
	["433603"] = require("@self/433603"),
	["383879"] = require("@self/383879"),
	["383878"] = require("@self/383878"),
	["383875"] = require("@self/383875")
} :: { [string]: { CollectionEntry } }